BBBB BBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXBBBBBXX
    XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XX
        FFFFFFFFFFFFFFFFFFFFFFFFF
        BB BBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFF FFFXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        BBBBB
    XXXXXX
XXXXXX