BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXX gettext(u'Invalid credentials.') XXXXXXXXX  gettext(u'Note that both fields are case-sensitive.') XXXX
        XXXXXX
    BBBBB
    XXXXX XXXXXXXXBBB BBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXBBBBBBBBBB
        BBB BBBBB BB BBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Log in') XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Reset My Password') XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXX XXXXX XXX XXXXXXXXXXXXX XXXXXXXX XX XXXXXXX XXX XXXXXXXXX XXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXX XXX XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XX XXX XXXX XXXXXX XXXXXXX XX XXXXXX XXXXXXX XXXX XXX XXXXXX XXXXXXXXX XXXXXX XXXXXX XXX XXXXXXXXXXX XXXXX XX XXXXXX XXX XX XXXXXX XXXXXXX XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXX
BBBBBBBB