BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXX ngettext(u'Please correct the error below.', u'Please correct the errors below.', count) SSSSSS SSSSSSS SSS SSSSS SSSSSSPPPPPP PPPPPPP PPP PPPPPP PPPPPPXXXX
        XXXXXX
    BBBBB
    XXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                 gettext(u"Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly.") 
            XXXXXX
        XXXXXX
        BBB BBBBB BB BBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Change my password') XXXXXXXXX
              XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXX
    XXXXXX

BBBBBBBB