BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXX ngettext(u'Please correct the error below.', u'Please correct the errors below.', count) SSSSSS SSSSSSS SSS SSSSS SSSSSSPPPPPP PPPPPPP PPP PPPPPP PPPPPPXXXX
        XXXXXX
    BBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB
        BBB BBBBB BB BBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'loading') XXXX XXXXXXXXXXXXXXXXXX gettext(u'Reset My Password') XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXXX
BBBBBBBB
