BBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBBBB
XXXXXX XXXXXXXXXXXXXXXX
XXXXXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXX XX
    XXXXX XX
    XXXXXX XX
X
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB