BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
	BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB
	BBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBB

	XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
		BBB BBBB BBBBB BB BBBBBB
			XXXXXXXX
		BBBBBB
	XXXXXXX
BBBBBBBB