BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXXXXBBBBBXX

XXXXXXXXX XXXXXXXXXXXXX XX
   XXXXFFFFFFFFXXXXX
   
   XXXXXXX
     XXXXXXXXXXX
       XXX XXXXXXXXXXXXXXXXXXXXXX
     BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
       BB BBB BBBBBBBBBBBBBBBBBBBBBB
         XXXBB BBBBBBBBBBBBBB XXXXXXXXXXXXXXXXBBBBBXFFFFFFFF
         BB BBBBBBBBBBBBBBBXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXFFFFFFFFFXX XXXXXXXFFFFFFFFFX XXBBBBB
         XXXXX
       BBBBB
     BBBBBB
     BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX gettext(u'Delete?') XXXXXBBBBB
     XXXXXXXXXXXXX

     XXXXXXX
     BBB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXFFFFFFFFFFXXXXXXXXXXXX
        BBBBB
        XXX XXXXXXXXXXXXXXX BBBBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXBBBBBBB BBBBBBBBBBBB XXXXXXXXXXBBBBBX
             XXXXXBB BBB BBBBBBBBBBBBBBBBXXXXXBBBBBXX
        XXX XXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBB
          
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Change') XXXXBBBBB
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXX gettext(u'View on site') XXXXBBBBB
            XXXXBBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          
          BBBBBBBBB
          BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
            BBB BBBB BB BBBBBBBB
              BBB BBBBB BB BBBB
                BB BBBBBBBBBBBBBBBBBBBBB  BBBBB
              BBBBBB
            BBBBBB
          BBBBBB
          BBBBBBBBBBBB
        XXXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
          BBB BBBB BB BBBBBBBB
            BBB BBBBB BB BBBB
              BB BBB BBBBBBBBBBBBBBBBBBBBB
              XXXBB BBBBBBBBBBBBBBBB XXXXXXXXXXXXXXBBBBBX
              BB BBBBBBBBBBBBBBBBB
                  XXXXXXX
              BBBB
                  
                  
              BBBBB
              XXXXX
              BBBBB
            BBBBBB
          BBBBBB
        BBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
        BBBBB
        XXXXX
     BBBBBB
     XXXXXXXX
   XXXXXXXX
XXXXXXXXXXX
  XXXXXX
XXXXXX
