BBBB BBBB
XXXX XXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBBBBBBBBB BBBBBBBBBBBXXXXXXX BBBBBBB BBBBBBBBBBBXXXXXXXXBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Run the selected action') X XXXXXXXXXXXX XXXXXXXFFFFFFFFFXX gettext(u'Go') XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFXXXXXXXXX
        BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXX gettext(u'Click here to select the objects across all pages') XX gettext(u'Select all %(total_count)s %(module_name)s') SSSSSS SSS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Clear selection') XXXXXXXXXXX
        BBBBB
    BBBBB
XXXXXX
