BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBB
  
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  BB BBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XX
  BBBBB
  BB BBBBBBBBBB BB BBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBB
  
  BB BBB BBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBB
    XXXXXXX
      XXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX
    XXXXXXXX
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBB


BBBBBBBB

BBBBB BBBBBBBBB XXXX XXXXXX XXXXXXXXXXXBBBBBBBB

BB BBB BBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX FFFFFFFF
XXXXXX
BBBBBBBB
BBBBB

BBBBB BBBBBBBXXXXBBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXXXXX
          BBBBB BBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBB
            XXXX
              BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB
              XX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX
                 gettext(u'Add %(name)s') SSS SSSSSSSS
              XXXX
            XXXXX
            BBBBB
          BBBBBBBB
        XXXXX
    BBBBBBBB
    BB BBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B gettext(u'Please correct the error below.') BBBB gettext(u'Please correct the errors below.') BBBBB
        XXXX
        
    BBBBB
    XXXX XXXXXXXXXXXXXBB BBBBBBBBBBBBBB XXXXXXXXBBBBBX XXXXXXXXXXXXXXXX
      BBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBB
      BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB

      BBBBB BBBBBBB
        BB BBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Filter') XXXXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
          XXXXXX
        BBBBB
      BBBBBBBB

      XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXBBBBBBBBBB
      BB BBBBBBBBBB
        XXXXXXXXXXX
      BBBBB

      BBBBB BBBBBBBBBBB
          BB BBBBBBBBBBB BBB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBBBBBBBB BB
          BB BBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBB
      BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBB
      XXXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
