BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB

BBBBB BBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXBBBBBBBB

BBBBB BBBBBBBXXXXBBBBBBBB

BBBBB BBBBBBBBB XXXX XXXXXX XXXXXXXXXXXBBBBBBBB

BB BBB BBBBBBBB
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
XXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXFFFFFFFFXXXXBBBBFFFFFFFFBBBBB
XXXXXXXX BB BBB gettext(u'Add %(name)s') SSS SSSSSSSSBBBBFFFFFFFFFFFFFFFFFFBBBBB
XXXXXX
BBBBBBBB
BBBBB

BBBBB BBBBBBBXXXX XXXXXXXXXXXXXXXXXX
BBBBB BBBBBBBBBBBB
BB BBBBBBBB BBB BBBBBBBB
  XXX XXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBB
    XXXX
        BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
        XX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX gettext(u'History') XXXX
    XXXXX
    BB BBBBBBBBBBBBBBBBXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'View on site') XXXXXXXXXBBBBB
    BBBBBBBB
  XXXXX
BBBBBBBBBB
BBBBBBBB
XXXXX BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
XXXXX
BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXBBBBB
BB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXBBBBB
BB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BB BBBBBB
    XX XXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBB BB B gettext(u'Please correct the error below.') BBBB gettext(u'Please correct the errors below.') BBBBB
    XXXX
    
BBBBB

BBBBB BBBBBBBBBB
BBB BBBBBBBB BB BBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
BBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX
            BB BBBBBBBBB BBB BBB
                XXXXXXXXXXXXXXXXXX
            BBBBBX
    XXXXXXXXX
BBBBBBBB


BBBBBBBBBBBBBBBBBBBBBB

XXXXXX
XXXXXXXXXXXXX
BBBBBBBB
