BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXBBBBBBBB

BBBBB BBBBBBBXXXXXBBBBBBBB

BBBBB BBBBBBBBB XXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX

BB BBBBBBBB
    BBB BBB BB BBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXX
        XXXXXXX
        XXXXXXXXX
            XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXX gettext(u'Models in the %(name)s application') SSSSSS SS SSS SSSSSSSS SSSSSSSSSSSXXXXXX
        XXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBB
            XXX XXXXXXXXXXXXXFFFFFXX
            BB BBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXX
            BBBBB

            BB BBBBBBBBBBBBB
                XXXXXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Add') XXXXXXXXX
            BBBB
                XXXXXXXXXXXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBB
                XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Change') XXXXXXXXX
            BBBB
                XXXXXXXXXXXXXXX
            BBBBB
            XXXXX
        BBBBBB
        XXXXXXXX
        XXXXXX
    BBBBBB
BBBB
    XXX gettext(u"You don't have permission to edit anything.") XXXX
BBBBB
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Recent actions') XXXXX
        XXXX gettext(u'My actions') XXXXX
            BBBB BBB
            BBBBBBBBBBBBB BB BB BBBBBBBBB BBBBBBBB BBBB
            BB BBB BBBBBBBBB
            XXX gettext(u'None available') XXXX
            BBBB
            XXX XXXXXXXXXXXXXXXXXXX
            BBB BBBBB BB BBBBBBBBB
            XXX XXXXXXXBB BBBBBBBBBBBBBBBBBXXXXXXXBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXBBBBBXX
                BB BBBBBBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBBBB
                    
                BBBB
                    XX XXXXXXXXXXXX
                BBBBB
                XXXXX
                BB BBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXX XXXXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXX
                BBBB
                    XXXXX XXXXXXXXXXX XXXXXXX gettext(u'Unknown content') XXXXXXX
                BBBBB
            XXXXX
            BBBBBB
            XXXXX
            BBBBB
    XXXXXX
XXXXXX
BBBBBBBB
