BBBB BBBB BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
BB BBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save') X XXXXXXXXXXXXXXX XXXXXXXXXXXX XXBBBBB
BB BBBBBBBBBBBBBBBB
    BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXXXXX
BBBBB
BB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save as new') X XXXXXXXXXXXXXXXXX XXBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save and add another') X XXXXXXXXXXXXXXXXXX XXBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Save and continue editing') X XXXXXXXXXXXXXXXX XXBBBBB
XXXXXX
