BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXX XXX XXXXXXXXXX
    XXXXXXX XXX XXXX XXX XXXXXXX XX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
XXXXXX

FFFF
BBBBBBBB