BBBBBBB BBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
XXXXXX

FFFF
BBBBBBBB