XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    BBBB BBBB BBBBBB BBBBBBBB BBBBBBBB BBBBBBB

    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XX

    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBBBBB

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB
    BBBBBBBBBBBBB BBBBBB

    BBBBBBBBBB BBB
    BBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBB

    XXXXXXXFFFFFFFFFFFFFFF X XXXXXXXX

    BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XX
    BBBBBBBBBBB

    XXXXXX XXXXXXXXXXXXXXXX
        FFFF
    XXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXBBB BBBXX
BBBBB BBBB
    XXXXXXX XX XX XXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBB          
                XXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXX
                BBBBB
                XXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            BBBB
                 XXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            BBBBB
            XXXXX
XXX
    XXXX XXXXXXXXXXXXX
        FFFF

        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXX XXXXXX
                XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            BBBBB BBBBBBBBBBBBBBBBBBBBBB
        XXXXXX

        BBBBB BBBBBBBBBBBBFFFFBBBBBBBB
    XXXXXX

    BBBBBBBBBB BBB
    BBBBBBBBBB
    BBBBBBBBBBBBB
BBBBBBBB
XXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX X
        XXX XXXXXXXXX X XXX
        XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
        XX XXXXXX X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX X XXXX XX XXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X XX
        XXXXXX X XXXXXX X XXXXXXXXXX
        XX XXXXXXX X XX XXXXXX X XX
        XX XXXXXXX X XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXX
        X
    XXX

    XXX XXX X XXXXXXXXXXXXXXXX
    XXX XXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
     XXXXXX XXXXXXXXX XX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX
            XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXX
        X
    X
XXX

XXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
FFFF
XXXXXXX