BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
	BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB
	BBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBB

	XXXXXXX XXX XX XXX
		XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XX XXXX XXXX XXXX XXXXXXX XX XXXXXXXX XXXXXXXXX XXXXX XXX XXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXX XXXXXX XXXXXXX XX XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
	XXXXXXXXXXXX

	BB BBBBBBBBBBBBBBBBBB
		XXXX gettext(u'Welcome! ☺') XXXXX
		 gettext(u'Add a Processing Node') 
		BBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
			XXX
			 gettext(u' \n\t\t\t\tTo get started, "%(add_processing_node)s". A processing node is a computer running an instance of %(nodeodm_link)s or some other software that implements this %(api_link)s.\n\t\t\t')  
				SS SSS SSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS S SSSSSSSSSS SSSS SS S SSSSSSSS SSSSSSS SS SSSSSSSS SS SSSSSSSSSSSSSSSS SS SSSS SSSSS SSSSSSSS SSSS SSSSSSSSSS SSSS SSSSSSSSSSSSS
			
			XXXX
		BBBBBBB
		XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
		
	BBBB
		
		BB BBBBBBBB
			XXXX gettext(u'Welcome! ☺') XXXXX
			 gettext(u'Select Images and GCP') 
			XXX
				 gettext(u' To create a map, press the "%(upload_images)s" button, or drag and drop some images into a project. ')  SS SSSSSS S SSSS SSSSS SSS SSSSSSSSSSSSSSSSSSS SSSSSSS SS SSSS SSS SSSS SSSS SSSSSS SSSS S SSSSSSSS 
			XXXX
			XXX
				XXXX
					XXXX gettext(u'You need at least 5 images') XXXXX
					XXXX gettext(u'Images must overlap by 65%% or more') XXXXX
					XXXX gettext(u'For great 3D, images must overlap by 83%%') XXXXX
					XXXX gettext(u'A <a href="https://github.com/OpenDroneMap/OpenDroneMap/wiki/Running-OpenDroneMap#running-odm-with-ground-control" target="_blank">GCP file</a> is optional, but can increase georeferencing accuracy') XXXXX
				XXXXX
			XXXX
		BBBBB

		XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

	BBBBB
BBBBBBBB
