BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
	BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB
	BBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBB

	XXXX XXXXXXXXXXXX 
		BBB BBBB BBBBB BB BBBBBB
			XXXXXXXX
		BBBBBB
	XXXXXXX

BBBBBBBB
