BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BB

BBBBB BBBBBBB

BBBB BBBBBBBBBBBBB BBBB BBBBBBBBBBBBBB
BBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBB

XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
	XXXX
		XXXX gettext(u'Hostname') XXXXX
		XXXXXXXXX
	XXXXX
	XXXX
		XXXX gettext(u'Port') XXXXX
		XXXXXXXXX
	XXXXX
	XXXX
		XXXX gettext(u'API Version') XXXXX
		XXXXXXXXX
	XXXXX
	XXXX
		XXXX gettext(u'Queue Count') XXXXX
		XXXXXXXXX
	XXXXX
	XXXX
		XXXX gettext(u'Last Refreshed') XXXXX
		XXXXFFFFFFFFF  gettext(u'ago')  XFFFFFFFFFXXXXXX XXXX XXXXX XXXXXXXXX XXX
	XXXXX
	XXXX
		XXXX gettext(u'Options (JSON)') XXXXX
		XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX
XXXXXXXX
BB BBBBBBBBBBBBBBBBB 
XXXX XXXXXXXXXXXXXXXXXXXX
	XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  gettext(u'Edit') XXXXXXXXX
	XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Delete') XXXXXXXXX
XXXXXX
BBBBB

BBBBBBBB
