BBBB BBBBBBBBBBBBBBBB

BBB BBBBB BB BBBB
XXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXBBBBBXX
    XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFFFFFFFFFFFF
    BB BBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFF FFFXXXXXXX
    BBBBB
    BB BBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    BBBBB
XXXXXX
BBBBBB